#@TYPE: Machine
#@NAME: COGIP RaspberryPi Zero WiFi Development Board
#@DESCRIPTION: Machine configuration for the COGIP RaspberryPi Zero  WiFi board (https://www.raspberrypi.org/blog/raspberry-pi-zero-w-joins-family/)

MACHINE = "cogip-raspberrypi0-wifi"

require conf/machine/raspberrypi0-wifi.conf
require conf/machine/cogip-rpi-base.inc

KERNEL_DEVICETREE = " \
    bcm2835-rpi-zero-w.dtb \
"

COGIP_BOOT_FILES += " \
    ${KERNEL_DEVICETREE} \
    rpi-bootfiles/fixup.dat \
    rpi-bootfiles/start.elf \
"
